title:              Brandi Christiano
email:              brandi.christiano@utexas.edu
description:        PhD student studying foraging ecology of bats in Texas and Panama
author:             Start Bootstrap
url:                "https://brandiMchristiano.github.io"

# Social Profiles
twitter_username:   BMChristiano

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/Posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
