title:              Brandi Christiano
email:              brandi.christiano@utexas.edu
description:        PhD student studying foraging ecology of bats in Texas and Panama
author:             BMC
url:                "https://brandiMchristiano.github.io"

# Social Profiles
twitter_username:   BMChristiano

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
